create table if not exists public.notifications (
  id int8 generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  catalogue_item_id uuid references public.catalogue(id) on delete set null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

create policy "Users can only access their own notifications"
  on public.notifications
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
